version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "14"
      - checkout
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run: |
          mkdir tmp
          mkdir tmp/workspace
          ls
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - udagram-api/build
            - udagram-frontend/www
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy Frontend
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy Backend end
          command: |
            npm run backend:deploy
workflows:
  udagram:
    jobs:
      - build
      - deploy:
          requires:
            - build
